/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProfitAndLossService } from "../profitAndLoss.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProfitAndLossCreateInput } from "./ProfitAndLossCreateInput";
import { ProfitAndLoss } from "./ProfitAndLoss";
import { ProfitAndLossFindManyArgs } from "./ProfitAndLossFindManyArgs";
import { ProfitAndLossWhereUniqueInput } from "./ProfitAndLossWhereUniqueInput";
import { ProfitAndLossUpdateInput } from "./ProfitAndLossUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProfitAndLossControllerBase {
  constructor(
    protected readonly service: ProfitAndLossService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProfitAndLoss })
  @nestAccessControl.UseRoles({
    resource: "ProfitAndLoss",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ProfitAndLossCreateInput,
  })
  async createProfitAndLoss(
    @common.Body() data: ProfitAndLossCreateInput
  ): Promise<ProfitAndLoss> {
    return await this.service.createProfitAndLoss({
      data: data,
      select: {
        cogs: true,
        createdAt: true,
        grossProfit: true,
        id: true,
        incomeBeforeTax: true,
        incomeTax: true,
        netIncome: true,
        nonOperatingExpenses: true,
        nonOperatingIncome: true,
        operatingExpenses: true,
        operatingIncome: true,
        revenue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProfitAndLoss] })
  @ApiNestedQuery(ProfitAndLossFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProfitAndLoss",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async profitAndLosses(
    @common.Req() request: Request
  ): Promise<ProfitAndLoss[]> {
    const args = plainToClass(ProfitAndLossFindManyArgs, request.query);
    return this.service.profitAndLosses({
      ...args,
      select: {
        cogs: true,
        createdAt: true,
        grossProfit: true,
        id: true,
        incomeBeforeTax: true,
        incomeTax: true,
        netIncome: true,
        nonOperatingExpenses: true,
        nonOperatingIncome: true,
        operatingExpenses: true,
        operatingIncome: true,
        revenue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProfitAndLoss })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfitAndLoss",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async profitAndLoss(
    @common.Param() params: ProfitAndLossWhereUniqueInput
  ): Promise<ProfitAndLoss | null> {
    const result = await this.service.profitAndLoss({
      where: params,
      select: {
        cogs: true,
        createdAt: true,
        grossProfit: true,
        id: true,
        incomeBeforeTax: true,
        incomeTax: true,
        netIncome: true,
        nonOperatingExpenses: true,
        nonOperatingIncome: true,
        operatingExpenses: true,
        operatingIncome: true,
        revenue: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProfitAndLoss })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfitAndLoss",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ProfitAndLossUpdateInput,
  })
  async updateProfitAndLoss(
    @common.Param() params: ProfitAndLossWhereUniqueInput,
    @common.Body() data: ProfitAndLossUpdateInput
  ): Promise<ProfitAndLoss | null> {
    try {
      return await this.service.updateProfitAndLoss({
        where: params,
        data: data,
        select: {
          cogs: true,
          createdAt: true,
          grossProfit: true,
          id: true,
          incomeBeforeTax: true,
          incomeTax: true,
          netIncome: true,
          nonOperatingExpenses: true,
          nonOperatingIncome: true,
          operatingExpenses: true,
          operatingIncome: true,
          revenue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProfitAndLoss })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfitAndLoss",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProfitAndLoss(
    @common.Param() params: ProfitAndLossWhereUniqueInput
  ): Promise<ProfitAndLoss | null> {
    try {
      return await this.service.deleteProfitAndLoss({
        where: params,
        select: {
          cogs: true,
          createdAt: true,
          grossProfit: true,
          id: true,
          incomeBeforeTax: true,
          incomeTax: true,
          netIncome: true,
          nonOperatingExpenses: true,
          nonOperatingIncome: true,
          operatingExpenses: true,
          operatingIncome: true,
          revenue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
