/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReportsService } from "../reports.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReportsCreateInput } from "./ReportsCreateInput";
import { Reports } from "./Reports";
import { ReportsFindManyArgs } from "./ReportsFindManyArgs";
import { ReportsWhereUniqueInput } from "./ReportsWhereUniqueInput";
import { ReportsUpdateInput } from "./ReportsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReportsControllerBase {
  constructor(
    protected readonly service: ReportsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reports })
  @nestAccessControl.UseRoles({
    resource: "Reports",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ReportsCreateInput,
  })
  async createReports(
    @common.Body() data: ReportsCreateInput
  ): Promise<Reports> {
    return await this.service.createReports({
      data: data,
      select: {
        createdAt: true,
        id: true,
        reportContent: true,
        reportType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reports] })
  @ApiNestedQuery(ReportsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reports",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reportsItems(@common.Req() request: Request): Promise<Reports[]> {
    const args = plainToClass(ReportsFindManyArgs, request.query);
    return this.service.reportsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        reportContent: true,
        reportType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reports })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reports",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reports(
    @common.Param() params: ReportsWhereUniqueInput
  ): Promise<Reports | null> {
    const result = await this.service.reports({
      where: params,
      select: {
        createdAt: true,
        id: true,
        reportContent: true,
        reportType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reports })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reports",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ReportsUpdateInput,
  })
  async updateReports(
    @common.Param() params: ReportsWhereUniqueInput,
    @common.Body() data: ReportsUpdateInput
  ): Promise<Reports | null> {
    try {
      return await this.service.updateReports({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          reportContent: true,
          reportType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reports })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reports",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReports(
    @common.Param() params: ReportsWhereUniqueInput
  ): Promise<Reports | null> {
    try {
      return await this.service.deleteReports({
        where: params,
        select: {
          createdAt: true,
          id: true,
          reportContent: true,
          reportType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
