/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ArApInvoicesService } from "../arApInvoices.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ArApInvoicesCreateInput } from "./ArApInvoicesCreateInput";
import { ArApInvoices } from "./ArApInvoices";
import { ArApInvoicesFindManyArgs } from "./ArApInvoicesFindManyArgs";
import { ArApInvoicesWhereUniqueInput } from "./ArApInvoicesWhereUniqueInput";
import { ArApInvoicesUpdateInput } from "./ArApInvoicesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ArApInvoicesControllerBase {
  constructor(
    protected readonly service: ArApInvoicesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ArApInvoices })
  @nestAccessControl.UseRoles({
    resource: "ArApInvoices",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ArApInvoicesCreateInput,
  })
  async createArApInvoices(
    @common.Body() data: ArApInvoicesCreateInput
  ): Promise<ArApInvoices> {
    return await this.service.createArApInvoices({
      data: data,
      select: {
        createdAt: true,
        description: true,
        discounts: true,
        dueDate: true,
        id: true,
        paymentTerms: true,
        penalties: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ArApInvoices] })
  @ApiNestedQuery(ArApInvoicesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ArApInvoices",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async arApInvoicesItems(
    @common.Req() request: Request
  ): Promise<ArApInvoices[]> {
    const args = plainToClass(ArApInvoicesFindManyArgs, request.query);
    return this.service.arApInvoicesItems({
      ...args,
      select: {
        createdAt: true,
        description: true,
        discounts: true,
        dueDate: true,
        id: true,
        paymentTerms: true,
        penalties: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ArApInvoices })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArApInvoices",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async arApInvoices(
    @common.Param() params: ArApInvoicesWhereUniqueInput
  ): Promise<ArApInvoices | null> {
    const result = await this.service.arApInvoices({
      where: params,
      select: {
        createdAt: true,
        description: true,
        discounts: true,
        dueDate: true,
        id: true,
        paymentTerms: true,
        penalties: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ArApInvoices })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArApInvoices",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ArApInvoicesUpdateInput,
  })
  async updateArApInvoices(
    @common.Param() params: ArApInvoicesWhereUniqueInput,
    @common.Body() data: ArApInvoicesUpdateInput
  ): Promise<ArApInvoices | null> {
    try {
      return await this.service.updateArApInvoices({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          discounts: true,
          dueDate: true,
          id: true,
          paymentTerms: true,
          penalties: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ArApInvoices })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArApInvoices",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteArApInvoices(
    @common.Param() params: ArApInvoicesWhereUniqueInput
  ): Promise<ArApInvoices | null> {
    try {
      return await this.service.deleteArApInvoices({
        where: params,
        select: {
          createdAt: true,
          description: true,
          discounts: true,
          dueDate: true,
          id: true,
          paymentTerms: true,
          penalties: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
