/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReconciliationService } from "../reconciliation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReconciliationCreateInput } from "./ReconciliationCreateInput";
import { Reconciliation } from "./Reconciliation";
import { ReconciliationFindManyArgs } from "./ReconciliationFindManyArgs";
import { ReconciliationWhereUniqueInput } from "./ReconciliationWhereUniqueInput";
import { ReconciliationUpdateInput } from "./ReconciliationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReconciliationControllerBase {
  constructor(
    protected readonly service: ReconciliationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reconciliation })
  @nestAccessControl.UseRoles({
    resource: "Reconciliation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ReconciliationCreateInput,
  })
  async createReconciliation(
    @common.Body() data: ReconciliationCreateInput
  ): Promise<Reconciliation> {
    return await this.service.createReconciliation({
      data: data,
      select: {
        bankStatementBalance: true,
        createdAt: true,
        difference: true,
        id: true,
        ledgerBalance: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reconciliation] })
  @ApiNestedQuery(ReconciliationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reconciliation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reconciliations(
    @common.Req() request: Request
  ): Promise<Reconciliation[]> {
    const args = plainToClass(ReconciliationFindManyArgs, request.query);
    return this.service.reconciliations({
      ...args,
      select: {
        bankStatementBalance: true,
        createdAt: true,
        difference: true,
        id: true,
        ledgerBalance: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reconciliation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reconciliation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reconciliation(
    @common.Param() params: ReconciliationWhereUniqueInput
  ): Promise<Reconciliation | null> {
    const result = await this.service.reconciliation({
      where: params,
      select: {
        bankStatementBalance: true,
        createdAt: true,
        difference: true,
        id: true,
        ledgerBalance: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reconciliation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reconciliation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ReconciliationUpdateInput,
  })
  async updateReconciliation(
    @common.Param() params: ReconciliationWhereUniqueInput,
    @common.Body() data: ReconciliationUpdateInput
  ): Promise<Reconciliation | null> {
    try {
      return await this.service.updateReconciliation({
        where: params,
        data: data,
        select: {
          bankStatementBalance: true,
          createdAt: true,
          difference: true,
          id: true,
          ledgerBalance: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reconciliation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reconciliation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReconciliation(
    @common.Param() params: ReconciliationWhereUniqueInput
  ): Promise<Reconciliation | null> {
    try {
      return await this.service.deleteReconciliation({
        where: params,
        select: {
          bankStatementBalance: true,
          createdAt: true,
          difference: true,
          id: true,
          ledgerBalance: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
